// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID?.trim();
const ENV_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
const DERIVED_SUPABASE_URL = SUPABASE_PROJECT_ID
  ? `https://${SUPABASE_PROJECT_ID}.supabase.co`
  : undefined;
const SUPABASE_URL = ENV_SUPABASE_URL || DERIVED_SUPABASE_URL;

if (!SUPABASE_URL) {
  throw new Error(
    "Missing Supabase URL. Set VITE_SUPABASE_URL or VITE_SUPABASE_PROJECT_ID in your environment."
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Missing VITE_SUPABASE_PUBLISHABLE_KEY in your environment.");
}

if (ENV_SUPABASE_URL && DERIVED_SUPABASE_URL && ENV_SUPABASE_URL !== DERIVED_SUPABASE_URL) {
  console.warn(
    `Supabase URL mismatch detected. Using explicit VITE_SUPABASE_URL (${ENV_SUPABASE_URL}) over derived URL (${DERIVED_SUPABASE_URL}).`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});